# Generated by Django 3.2.16 on 2023-01-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiderModel',
            fields=[
                ('RideID', models.AutoField(primary_key=True, serialize=False)),
                ('RiderID', models.CharField(max_length=500)),
                ('FromAddress', models.CharField(max_length=500)),
                ('ToAddress', models.CharField(max_length=500)),
                ('DateTime', models.DateTimeField()),
                ('AvailableAssets', models.IntegerField()),
                ('TravelMedium', models.CharField(choices=[('B', 'Bus'), ('C', 'Car'), ('T', 'Train')], max_length=1)),
            ],
        ),
    ]
