# Generated by Django 3.2.16 on 2023-01-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiderApp', '0002_auto_20230108_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridermodel',
            name='DateTime',
            field=models.DateField(),
        ),
    ]
