# Generated by Django 3.2.16 on 2023-01-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiderApp', '0003_alter_ridermodel_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridermodel',
            name='RiderID',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ridermodel',
            name='Status',
            field=models.CharField(choices=[('X', 'DELIVERED'), ('O', 'MATCHED'), ('-', 'POSTED')], default='-', max_length=1),
        ),
    ]
