# Generated by Django 3.2.16 on 2023-01-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequesterModel',
            fields=[
                ('RequestID', models.AutoField(primary_key=True, serialize=False)),
                ('RequesterID', models.CharField(max_length=500)),
                ('FromAddress', models.CharField(max_length=500)),
                ('ToAddress', models.CharField(max_length=500)),
                ('DateTime', models.DateTimeField()),
                ('NumberOfAssets', models.IntegerField()),
                ('AssetType', models.CharField(choices=[('L', 'LAPTOP'), ('T', 'TRAVEL_BAG'), ('P', 'PACKAGE')], max_length=1)),
                ('Senstivity', models.CharField(choices=[('H', 'HIGHLY_SENSITIVE'), ('S', 'SENSITIVE'), ('N', 'NORMAL')], max_length=1)),
            ],
        ),
    ]
