# Generated by Django 3.2.16 on 2023-01-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequesterApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestermodel',
            name='RideID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='requestermodel',
            name='Status',
            field=models.CharField(choices=[('X', 'DELIVERED'), ('O', 'MATCHED'), ('-', 'REQUESTED')], default='-', max_length=1),
        ),
        migrations.AlterField(
            model_name='requestermodel',
            name='AssetType',
            field=models.CharField(choices=[('L', 'LAPTOP'), ('T', 'TRAVEL_BAG'), ('P', 'PACKAGE')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='requestermodel',
            name='Senstivity',
            field=models.CharField(choices=[('H', 'HIGHLY_SENSITIVE'), ('S', 'SENSITIVE'), ('N', 'NORMAL')], default='N', max_length=1),
        ),
    ]
