# Generated by Django 3.2.16 on 2023-01-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequesterApp', '0002_auto_20230108_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestermodel',
            name='DateTime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='requestermodel',
            name='RequesterID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='requestermodel',
            name='RideID',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='requestermodel',
            name='Status',
            field=models.CharField(choices=[('O', 'MATCHED'), ('X', 'DELIVERED'), ('-', 'REQUESTED')], default='-', max_length=1),
        ),
    ]
