# Generated by Django 3.2.16 on 2023-01-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequesterApp', '0003_auto_20230108_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestermodel',
            name='Status',
            field=models.CharField(choices=[('-', 'PENDING'), ('X', 'EXPIRED'), ('O', 'CONFIRMED')], default='-', max_length=1),
        ),
    ]
